apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-tech-ingress
  labels:
    app: app-tech
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app-tech-service
                port:
                  number: 8080