apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tech
  labels:
    app: app-tech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-tech
  template:
    metadata:
      labels:
        app: app-tech
    spec:
      containers:
        - name: app-tech
          image: wolwer/app-tech
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: DATA_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DATA_HOST
            - name: DATA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DATA_USERNAME
            - name: DATA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DATA_PASSWORD
            - name: DATA_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DATA_PORT
            - name: DATA_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DATA_DATABASE
            - name: DATA_URL
              value: jdbc:postgresql://monorail.proxy.rlwy.net:54078/railway
          resources:
            requests:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30