apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    app: app-tech
type: Opaque
data:
  DATA_USERNAME: cG9zdGdyZXM=  # "postgres" em base64
  DATA_PASSWORD: RUdERS00LUU2YUNBLURFMTEyNmY2ZTFEZWdkZ2cqNkY=  # "my-secret-pw" em base64
  POSTGRES_USER: cG9zdGdyZXM=  # "postgres" em base64