name: Manual Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        type: boolean
        description: 'Confirm destroy? Must be true to proceed.'
        required: true
        default: false

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm == true }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Initialize Terraform
        run: terraform init
        working-directory: path/to/your/terraform/config

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: path/to/your/terraform/config
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          TF_VAR_regionDefault: ${{ secrets.AWS_REGION }}
