name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply EKS and Security Group
      run: terraform apply -auto-approve -target=aws_alb.alb -target=aws_lb_listener.listener -target=aws_eks_access_entry.access-entry -target=aws_eks_access_policy_association.eks-policy -target=aws_eks_cluster.eks-cluster -target=aws_eks_node_group.node-group -target=aws_security_group.sg -target=aws_lb_target_group.tg

    - name: Terraform Apply Load Balancer Attachment
      run: terraform apply -auto-approve -target=aws_lb_target_group_attachment.attach -target=aws_instance.ec2
