name: Deploy to EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Set up AWS environment variables from secrets
        run: |
          mkdir -p ~/.aws
          echo "[lab]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[profile lab]" >> ~/.aws/config
          echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply EKS and Security Group
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -target=aws_alb.alb -target=aws_lb_listener.listener -target=aws_eks_access_entry.access-entry -target=aws_eks_access_policy_association.eks-policy -target=aws_eks_cluster.eks-cluster -target=aws_eks_node_group.node-group -target=aws_security_group.sg -target=aws_lb_target_group.tg

      - name: Terraform Apply Load Balancer Attachment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -target=aws_lb_target_group_attachment.attach -target=aws_instance.ec2

